# Generated by Django 4.2.1 on 2023-07-29 18:13

from django.db import migrations, models
import project.file_savers.file_convertor.txt_to_json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TxtToJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to=project.file_savers.file_convertor.txt_to_json.txt_to_json_file_saver)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=project.file_savers.file_convertor.txt_to_json.txt_to_json_file_saver)),
            ],
            options={
                'verbose_name': 'Txt -> json',
                'verbose_name_plural': 'Txt -> json',
            },
        ),
    ]
