# Generated by Django 4.2.1 on 2023-06-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, verbose_name='Id чата')),
                ('bot_token', models.CharField(max_length=150, verbose_name='Токен Бота')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название сайта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('list_api_link', models.URLField(verbose_name='Ссылка на список')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_name', models.CharField(max_length=20, verbose_name='Название json поля')),
                ('api_link', models.URLField(verbose_name='Ссылка на сегмент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.site')),
            ],
            options={
                'verbose_name': 'Сегмент',
                'verbose_name_plural': 'Сегменты',
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='Индивидуальный токен валюты')),
                ('sent', models.BooleanField(default=False, verbose_name='отправленно')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.site')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
                'unique_together': {('site', 'token')},
            },
        ),
        migrations.CreateModel(
            name='PairSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_name', models.CharField(max_length=20, verbose_name='Название json поля')),
                ('content', models.TextField(verbose_name='json контент')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.pair')),
            ],
            options={
                'verbose_name': 'Сегмент пары',
                'verbose_name_plural': 'Сегменты пары',
                'unique_together': {('json_name', 'pair')},
            },
        ),
    ]
