# Generated by Django 4.2.1 on 2023-06-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='json_scheme',
            field=models.TextField(default='', verbose_name='Схема обработки ответов'),
            preserve_default=False,
        ),
    ]
