# Generated by Django 4.2.1 on 2023-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_remove_pair_json_scheme_site_json_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='api_key',
            field=models.CharField(default='', max_length=100, verbose_name='Апи ключ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='api_key_field_name',
            field=models.CharField(default='', max_length=100, verbose_name='Название поля для api ключа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pairsegment',
            name='content',
            field=models.TextField(blank=True, verbose_name='json контент'),
        ),
    ]
