# Generated by Django 4.2.1 on 2023-06-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_site_api_key_site_api_key_field_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='api_token_field_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название токена'),
        ),
        migrations.AddField(
            model_name='segment',
            name='api_token_place',
            field=models.CharField(choices=[('header', 'header'), ('body', 'body'), ('link', 'link')], default='', max_length=10, verbose_name='Место где хранится токен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segment',
            name='json_scheme',
            field=models.TextField(default='', verbose_name='Схема обработки ответов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='api_key_place',
            field=models.CharField(choices=[('header', 'header'), ('body', 'body'), ('link', 'link')], default='', max_length=10, verbose_name='Место где хранится ключ'),
            preserve_default=False,
        ),
    ]
