# Generated by Django 4.2.1 on 2023-06-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_segment_scheme_single_target_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='first_run',
            field=models.BooleanField(default=True, verbose_name='Первый запуск'),
        ),
        migrations.AddField(
            model_name='site',
            name='link_template',
            field=models.CharField(blank=True, max_length=100, verbose_name='Шаблон ссылки'),
        ),
    ]
