# Generated by Django 4.2.1 on 2023-06-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0007_site_first_run_site_link_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='segments_loaded',
            field=models.BooleanField(default=True, verbose_name='Сегменты загружены'),
        ),
    ]
