# Generated by Django 4.2.1 on 2024-02-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0009_alter_pair_segments_loaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='method',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post')], default='get', max_length=10, verbose_name='Метод запроса'),
        ),
    ]
